- README.md
This adds [dotnet-mono](https://github.com/TheAngryByrd/dotnet-mono) a tool for running dotnet core projects targeting.net full framework apps with mono.
> Added dotnet-mono

- README.md
Was `FluentBahave` now is `FluentBehave`.
> Fix misspelling of FluentBehave

- README.md
The Lambda tool got moved to a different repository with a couple other AWS tools. They are still project tools.
> Update AWS tools

- README.md
[`dotnet-xdt`](https://www.nuget.org/packages/dotnet-xdt/) is available as a global CLI tool, and [`DotNet.Xdt`](https://www.nuget.org/packages/DotNet.Xdt/) is a .NET Standard library for applying XDT.
The "classic" `dotnet-transform-xdt` remains available as a project-level tool for all .NET Core versions.
> Add `dotnet-xdt` CLI global tool

- README.md
I Wrote a small tool which is similar to "thanks" - it lists all packages of your project with their authors, github and nuget pages, and I thought about adding it to your list so people can see it. I hope you like it.
> Adding dotnet-thx to list of tools

- README.md
This PR corrects the following issues with the Coverlet entry:
1. The command name
1. The package ID
1. Links to the NuGet package instead of GitHub
> Correct coverlet entry

- README.md
The previous description is for the MinVer package rather than the minver-cli package.
> fix minver-cli description

- README.md
This PR adds [CSharpMinifierConsole](https://www.nuget.org/packages/CSharpMinifierConsole/) (`csmin`), which is a small and fast utility for minifying C# source by removing comments and unnecessary whitespace that's irrelevant to the behaviour of the code.
> Add C# Minifier (csmin/CSharpMinifierConsole)

- README.md
Hi, This is a PR to add a link to the .NET Global tool [base64urls](https://www.nuget.org/packages/base64urls/).
This tool offers similar experience as npm [base64\-url\-cli](https://www.npmjs.com/package/base64-url-cli) offers.
Thanks.
> add base64urls

- README.md
As of https://github.com/nil4/dotnet-transform-xdt/releases/tag/v2.1.0, in addition to the `dotnet-xdt` global tool, a couple more options are available:
- a .NET Standard 2.0 library, with no external dependencies, for custom XDT transformations
- a standalone executable, for .NET 4.6.1 or later, for automation on Windows PCs without .NET Core
Update README to reflect these new options.
> dotnet-xdt: add netstandard library/net461 executable

- README.md
dotnet-apim is added to the list which streamlines the deployment of Azure APIM.
> dotnet-apim is added

- README.md
New tool: depguard for .NET (simplified port of Go's depguard)
> Add depguard dotnet tool

- README.md
Snitch A tool that help you find transitive package references that can be removed.
(sorted now)
> Add snitch

- README.md
[ncbeauty](https://github.com/nulastudio/NetCoreBeauty) is a tool that can move a .NET Core app runtime components and dependencies into a sub-directory and make it beauty.
> Add ncbeauty

- README.md
Updated Azure API management install line to match the one specified on https://github.com/mirsaeedi/dotnet-apim.
> Updated Azure API Management install line

- README.md
The command line stated dotnet-toast, but that is for another tool, not for the readbin tool
> Fix install command line for dotnet-readbin

- README.md
Microsoft Excel Add-Ins developed with [Excel-DNA](https://github.com/Excel-DNA) are usually packaged up into a single `.xll` file for easier distribution. The `.xll` file contains all the components necessary to run the add-in, which usually include one or more .NET assemblies along with other resources the add-in uses such as images, ribbon `.xml` definitions and other configuration files.
[ExcelDna-Unpack](https://github.com/augustoproiete/exceldna-unpack) allows users to extract the resources of these packaged `.xll`
> Add exceldna-unpack dotnet tool

- README.md
Added my new `nuke-from-orbit` tool that deletes `bin` and `obj` directories from solutions.
> Add RendleLabs.NukeFromOrbit

- README.md
Jerrie Pelser has abandoned `dotnet-outdated` and ongoing development has moved.
> Update dotnet-outdated details

- README.md
This tool manages your todo list using the command line syntax and text file format of the shell script from http://todotxt.org/, originally from Life Hacker.
> Adds dotnet-todo

- README.md
Hello, I am the author of the `dotnet-tool-run` tool.
I have renamed this tool to `dotnex` just a few minutes ago, and I would like to update this reference that I added originally to this repository 😃 
You can verify the change of the name in the following URLs:
https://www.nuget.org/packages/dotnex/
https://www.nuget.org/packages/dotnet-tool-run/ (note the legacy note and the suggested tool)
https://github.com/piraces/dotnex
Thank you in advance and sorry for the inconvenience.
> Change dotnet-tool-run to dotnex
