natemcmaster/dotnet-tools

README.md
I created a little tool so you can install front-end packages without needing Node.js installed.
=> Add dotnet-unpkg

README.md
* adding [dotnet-doc](https://github.com/spboyer/dotnet-doc) to global tools list
* fixing md linting issues.
=> Add dotnet-doc to list

README.md
Also removed the request from the wanted section
=> Add dotnet-outdated

README.md
=> Added localappveyor global tool

README.md
=> Add dotnetrsa to the list

README.md
- Update certes package ID
- Add NuGet link for dotnet-certes
=> Add NuGet link for dotnet-certes

README.md
Not a super useful tool, but I thought it was kind of funny. Not sure if it's worth putting on this list.
=> Nyancat as a dotnet tool

README.md
=> Fake cli added

README.md
Dotnet core global tool for converting csproj files to the new format.
=> Add csproj conversion tool

README.md
Put correct author in the table
=> put correct author

README.md
Add coverlet to be able to generate coverage reports that can be used by Report Generator
=> Add coverlet

README.md, project-tools.md
Tools published by the [AltCover project](https://github.com/SteveGilham/altcover)
=> AltCover details

README.md
https://github.com/Hubert-Rybak/dotnet-warp/issues/2
=> React to dotnet-pack project rename

README.md
Adds [`recolor`](https://github.com/atifaziz/recolor) to list.
=> Add recolor tool

README.md
This is a great repo, @natemcmaster !
=> Add Obfuscar project site

README.md
.NET Global Tool to generate .gitignore files using gitignore.io
GitHub: https://github.com/liammoat/dotnet-giio
NuGet: https://www.nuget.org/packages/dotnet-giio
=> Added dotnet giio

README.md
=> Added tool - NukedBit.NRepo

README.md
This PR adds [CSharpSyntaxValidator](https://github.com/atifaziz/CSharpSyntaxValidator), which is a simple utility that validates a C# source for syntax errors.
=> Add CSharpSyntaxValidator (csval)

README.md
The https://github.com/ivanpaulovich/todo provides a todo list management in the terminal. It is extensible and simple.
=> Added todo list app

README.md
Hi!
This is a PR to add a link to the .NET global tool [git-rocket-filter](https://github.com/xoofx/git-rocket-filter)
Thanks!
=> Add git-rocket-filter

README.md
imgup is helpful in uploading images to imgur
namechk is helpful in checking if a nuget package name is available on nuget.org or not
=> Add dotnet-imgup & dotnet-namechk tools

README.md
=> Fixes #138 - octopus CLI

README.md
=> Add row for git-flow-version.

README.md
Markdown documentation generator tool
=> Added mddox tool.

README.md
Context: https://github.com/jonathanpeppers/boots
=> Add "boots" to README.md

README.md
Automatically commit changes to git on a set interval, ending with a squash merge to the original head
=> Added autocommit

README.md
Add [json2yaml](https://www.nuget.org/packages/json2yaml/)
=> Add json2yaml

README.md
Add [sharpfuzz](https://www.nuget.org/packages/SharpFuzz.CommandLine/). Resolves #141
=> Add sharpfuzz

README.md
Added missing project site and link
=> guid: Added project site

README.md
https://www.nuget.org/packages/PowerShell/
=> Add PowerShell (pwsh) global tool

README.md
I've recently been working on a dotnet global tool, hope you don't mind me adding it to your list of available tools :)
=> Adding dotnet-server

README.md, project-tools.md
Add the global tool "CertDump"
=> Add certdump

README.md
Adds the global tool "moniker" to the list
=> Add moniker

README.md
=> Add row for Orang

README.md
cc @AndreyAkinshin @adamsitnik
=> Add reference to BenchmarkDotNet global tool

README.md
=> Add entry for xamarin-android-binderator

README.md
Dotnet Execute Tool added to the list
=> dotnet-exec tool added to the list

README.md
👋 Thank you for this great list, I have consulted it numerous times and happy to finally list some tools myself.
=> Add assembly-differ and assembly-rewriter

README.md
=> dotnet-server fix

README.md
Roslynator is the best C# static analysis analyzer. Please add it!
=> Add roslynator

README.md
=> Add SpecSync global tool

README.md
Bruce is a command line Kerberos.NET management tool. https://syfuhs.net/bruce-a-command-line-kerberos-net-management-tool
=> Added Bruce

README.md
Added [kryptos](https://github.com/vijayshinva/kryptos)
=> Added kryptos

README.md
Hi 👋🏽 
I wanted to add my CLI tool called Az-Lazy.
=> added azlazy to the list

README.md, project-tools.md
Hi, can you please add the tool to your lists?
(Please excuse me, It is my secondary pull-request after a year , my first pul-request in vs-code and I have even done several mistakes at the first attempt so I have to re-create the branch. So peraps this pull request will be ok)
=> add dotnet-tools-updated

README.md
https://github.com/wivuu/Wivuu.AzCosmosCopy
=> Added azcosmoscopy

README.md
Add [dotnet-args](https://github.com/augustoproiete/dotnet-args) tool to the list.
=> Add dotnet-args tool

README.md
`dotnet-extract` is a .NET global tool to extract embedded resource files.
=> dotnet-extract

README.md
Add [dotnet-tool-run](https://www.nuget.org/packages/dotnet-tool-run/) tool to the list.
=> Add dotnet-tool-run tool
